import type { CliErrorContract } from "../types.js";

export const errorContracts: CliErrorContract[] = [
  { code: "E_URL_INVALID", message: "URL must be absolute (e.g. https://example.com)", retryable: false },
  {
    code: "E_SESSION_ID_INVALID",
    message: "sessionId may only contain letters, numbers, dot, underscore, and dash",
    retryable: false,
  },
  { code: "E_SESSION_NOT_FOUND", message: "Requested session was not found in state", retryable: false },
  { code: "E_SESSION_REQUIRED", message: "session is required for this command when target session cannot be inferred", retryable: false },
  { code: "E_SESSION_EXISTS", message: "Session id already exists", retryable: false },
  { code: "E_SESSION_UNREACHABLE", message: "Attached session endpoint is not reachable", retryable: true },
  { code: "E_SESSION_CONFLICT", message: "Reserved default session id has conflicting kind", retryable: false },
  { code: "E_TARGET_ID_INVALID", message: "targetId contains invalid characters", retryable: false },
  { code: "E_TARGET_NOT_FOUND", message: "Requested target was not found in session", retryable: false },
  { code: "E_TARGET_SESSION_UNKNOWN", message: "targetId is not mapped to a known session", retryable: false },
  { code: "E_TARGET_SESSION_MISMATCH", message: "targetId does not belong to the requested session", retryable: false },
  { code: "E_QUERY_INVALID", message: "Query input is invalid or missing", retryable: false },
  { code: "E_ASSERT_FAILED", message: "Pipeline assertion failed", retryable: false },
  { code: "E_WAIT_TIMEOUT", message: "wait condition did not complete before timeout", retryable: true },
  { code: "E_EVAL_SCRIPT_TOO_LARGE", message: "Evaluation script exceeds maximum supported length", retryable: false },
  { code: "E_EVAL_TIMEOUT", message: "evaluation did not complete before timeout", retryable: true },
  { code: "E_EVAL_RUNTIME", message: "evaluation failed in page context", retryable: false },
  { code: "E_EVAL_RESULT_UNSERIALIZABLE", message: "evaluation result is not JSON-serializable", retryable: false },
  { code: "E_SELECTOR_INVALID", message: "Selector query is invalid", retryable: false },
  { code: "E_CDP_INVALID", message: "CDP URL is invalid", retryable: false },
  { code: "E_CDP_UNREACHABLE", message: "CDP endpoint is not reachable", retryable: true },
  { code: "E_BROWSER_NOT_FOUND", message: "No compatible Chrome/Chromium binary found", retryable: false },
  { code: "E_BROWSER_START_FAILED", message: "Chrome/Chromium process failed to start", retryable: true },
  { code: "E_BROWSER_START_TIMEOUT", message: "CDP endpoint did not become ready in time", retryable: true },
  { code: "E_STATE_LOCK_TIMEOUT", message: "Timed out waiting for state lock", retryable: true },
  { code: "E_STATE_LOCK_IO", message: "State lock file I/O failed", retryable: true },
  { code: "E_UPDATE_METADATA", message: "Unable to fetch update metadata from package registry", retryable: true },
  { code: "E_UPDATE_PRECONDITION", message: "Update preconditions failed (dirty tree/branch/state)", retryable: false },
  { code: "E_UPDATE_APPLY_FAILED", message: "Update apply command failed", retryable: true },
  {
    code: "E_UPDATE_HEALTHCHECK_FAILED",
    message: "Updated runtime failed health verification and rollback could not recover",
    retryable: true,
  },
  { code: "E_UPDATE_ROLLBACK_NOT_AVAILABLE", message: "No rollback target found in update history", retryable: false },
  { code: "E_SKILL_MANIFEST_INVALID", message: "Skill manifest is missing required compatibility metadata", retryable: false },
  { code: "E_SKILL_SOURCE_NOT_FOUND", message: "Skill source directory was not found", retryable: false },
  { code: "E_SKILL_COMPAT_VERSION_MISMATCH", message: "Skill requires a different surfwright version range", retryable: false },
  {
    code: "E_SKILL_COMPAT_CONTRACT_SCHEMA_MISMATCH",
    message: "Skill requires a different contract schema version",
    retryable: false,
  },
  {
    code: "E_SKILL_COMPAT_CONTRACT_MISMATCH",
    message: "Skill requires a different contract fingerprint",
    retryable: false,
  },
  { code: "E_SKILL_INSTALL_ATOMIC_SWAP_FAILED", message: "Skill install/update atomic swap failed", retryable: true },
  { code: "E_INTERNAL", message: "Unexpected runtime failure", retryable: true },
];
